import NavLink from "@/components/nav-link";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav className="flex items-center h-14 justify-between px-4 z-40 text-sm sticky top-0 bg-white/50 backdrop-blur-md md:px-5  lg:px-10 ">
        <Link href={"/"} className="font-medium text-lg text-gray-900">
          TechDepot
        </Link>
        <div className="flex items-center gap-4">
          <NavLink href={"/dashboard"} className="text-gray-600">
            Home
          </NavLink>
          <NavLink href={"/dashboard/product"} className="text-gray-600">
            Products
          </NavLink>
          <NavLink href={"/dashboard/orders"} className="text-gray-600">
            Orders
          </NavLink>
        </div>
      </nav>
      {children}
    </>
  );
}
