import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav className="flex items-center h-14 justify-between px-4 md:px-5 lg:px-10">
        <Link href={"/"}>TechDepot</Link>
        <Link href={"/dashboard/product"}>products</Link>
      </nav>
      {children}
    </>
  );
}
